### ISSUE TITLE
Checking for Visual C++ occur fatal error

### ISSUE THREAD

**Issue by suidadabian** [VirtualBoBs/build-virtualbox-in-windows#4]
I installed Visual C++ 2010 in default paths, but run setup.python fail:

> E:\project\build-virtualbox-in-windows\script>call build_vbox.bat
>[+] Configure VirtualBox build setting
>
>Shell inheritance test: OK
>Source path: OK
>Checking for kBuild...
> Target architecture: amd64.
> Host architecture: amd64.
> Found kBuild: C:/VBoxBuild/VirtualBox/kBuild
> Found kBuild binaries: C:/VBoxBuild/VirtualBox/kBuild/bin/win.amd64
> Checking for Windows DDK v7.1...
> Found Windows DDK v7.1: C:/WinDDK/7600.16385.1
> Checking for Visual C++...
>fatal error: PathAbs(C:\Program Files (x86)\Microsoft Visual Studio 10.0) attempted to return filename with problematic characters in it (C:\PROGRA~2\Microsoft Visual Studio 10.0). The tool/sdk referenced will probably need to be copied or reinstalled to a location without 'spaces', '$', ';' or '&' in the path name. (Unless it's a problem with this script of course...)

should I install in other path or any solution?

**Comment by jidoc01** [comment]
It seems that the error comes not from ours but from `configure.vbs` in your downloaded VirtualBox project. And the problematic logic exists, I guess by your log, in `PathAbs` function.

I've not seen this type of error before and I'm not sure why it does not work in your environment, but, yes, as you said it might be resolved if you install VS to the other `location without 'spaces', '$', ';' or '&' `.
