### ISSUE TITLE
Completely failed to instantiate CLSID_VirtualBox: ERROR_SERVICE_REQUEST_TIMEOUT 0x8007041D.

### ISSUE THREAD

**Issue by suglove** [VirtualBoBs/build-virtualbox-in-windows#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jidoc01** [comment]
It seems that the problem is not related to our script.

And when you google it, there are a bunch of Q&As about the problem. Please try to find its solution by your own first.

**Comment by suglove** [comment]
thank you

When I finished compiling the software, it failed to start.&nbsp;I did a Google search and didn't find any questions, so I didn't know what was wrong.&nbsp;I think starting the GUI is a failure.&nbsp;Can the software be packaged into an installation package after compilation?











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VirtualBoBs/build-virtualbox-in-windows"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 中午1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VirtualBoBs/build-virtualbox-in-windows] Completely failed to instantiate CLSID_VirtualBox: ERROR_SERVICE_REQUEST_TIMEOUT 0x8007041D. (Issue #5)





 
It seems that the problem is not related to our script.
 
And when you google it, there are a bunch of Q&amp;As about the problem. Please try to find its solution by your own first.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
