### ISSUE TITLE
Windows On ARM64 support needed

### ISSUE THREAD

**Issue by sidd-kishan** [VirtualBoBs/build-virtualbox-in-windows#6]
Dear Team,
                    If we try to build vbox and specifically just VBoxUSB and VBoxUSBMon drivers for ARM64 then the projects like Windows on Raspberry pi can benifit as folks will be able to pass through the usb devices to Windows Subsystem for linux and utilize the linux drivers instead of waiting for or the  windows deivers to be released with the help of projects like USBIPD as it is waiting for Arm64 specific drivers ( issue: https://github.com/dorssel/usbipd-win/issues/233 ).

**Comment by jidoc01** [comment]
I'm sorry but I'm not sure the current version of VirtualBox officially supports Windows on ARM64. The link you referred also  says that it won't support ARM64 (https://forums.virtualbox.org/viewtopic.php?t=92857).

**Comment by sidd-kishan** [comment]
Yes, Is it posible if we try retarget the compilation to ARM64 i can help in testing out the retargated build

**Comment by jidoc01** [comment]
I think you came to a wrong place. We're not the official VirtualBox team, but Virtual'BoBs'.
