### ISSUE TITLE
error: Cannot find cl.exe (Visual C++) anywhere on your system. Check the build requirements.

### ISSUE THREAD

**Issue by xiaonaiquan** [VirtualBoBs/build-virtualbox-in-windows#7]
I'm using VS2010 and the path is correct, but I don't know why I get the following error:

Shell inheritance test: OK
Source path: OK
Checking for kBuild...
 Target architecture: amd64.
 Host architecture: amd64.
 Found kBuild:               C:/VBoxBuild/VirtualBox/kBuild
 Found kBuild binaries:      C:\VBoxBuild\VirtualBox\kBuild\bin\win.amd64
Checking for Windows DDK v7.1...
 Found Windows DDK v7.1:     C:/WinDDK/7600.16385.1
Checking for Visual C++...
error: Cannot find cl.exe (Visual C++) anywhere on your system. Check the build requirements.

**Comment by jidoc01** [comment]
We've tested our tool with VS 2010 Professional. Which version of VS2010 are you using? It does not mean that our tool  supports Professional version only, but I can say that it reliably runs on it. Or, it could help if you create an independent OS  environment (such as Virtual Machine and Container) and clean-install all the requirements.

**Comment by xiaonaiquan** [comment]
Yes, I installed VS 2010 Professional, And I can find cl.exe in" C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin", I don't know why configuation.vbs can't find this

**Comment by xiaonaiquan** [comment]
> We've tested our tool with VS 2010 Professional. Which version of VS2010 are you using? It does not mean that our tool supports Professional version only, but I can say that it reliably runs on it. Or, it could help if you create an independent OS environment (such as Virtual Machine and Container) and clean-install all the requirements.

Yes, I installed VS 2010 Professional, And I can find cl.exe in" C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin", I don't know why configuation.vbs can't find this.

**Comment by jidoc01** [comment]
You've installed Pro version. Then it should work in a normal situation.

Actually, the script `configuration.vbs` does not come from our tool but from the source code to compile. I guess there are a few possibilities:
1. The configuration is too old (i.e. the source code is obsolete) to support the recent environment.
2. The configuration is customized (tweaked) by users and it works differently from the official source code.

Where did you get the source code? Our tool works on the source code from the official website. Or, if it is so, then you can ask VirtualBox forum to get the answer, since this problem is not related to our scripts: https://forums.virtualbox.org/viewforum.php?f=10. And, as I said above, you can also give a try to a clean-install.

**Comment by jidoc01** [comment]
And if you find an answer, please let us know! It could help the others who are getting the same problem :D

**Comment by xiaonaiquan** [comment]
OK ,I will try to solve this problem, thank you for your answer.

**Comment by xiaonaiquan** [comment]
> You've installed Pro version. Then it should work in a normal situation.
> 
> Actually, the script `configuration.vbs` does not come from our tool but from the source code to compile. I guess there are a few possibilities:
> 
> 1. The configuration is too old (i.e. the source code is obsolete) to support the recent environment.
> 2. The configuration is customized (tweaked) by users and it works differently from the official source code.
> 
> Where did you get the source code? Our tool works on the source code from the official website. Or, if it is so, then you can ask VirtualBox forum to get the answer, since this problem is not related to our scripts: https://forums.virtualbox.org/viewforum.php?f=10. And, as I said above, you can also give a try to a clean-install.

May I ask which version of Virtualbox you have compiled?

**Comment by xiaonaiquan** [comment]
I solved this problem and the solution is as follows: it needs to be a full English system and English version VS2010 or change configure.vbs.

**Comment by jidoc01** [comment]
Thanks for the information! I will add the note into the project.
